language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

git:
  submodules: false

jobs:
  include:
    - stage: Test
      name: Testing
      script: yarn test
    - stage: Documentation
      name: 'Build Documentation'
      script: ./build-documentation.sh
    - stage: Submodule
      name: 'Update Submodule'
      script: ./update-submodule.sh
