language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

git:
  submodules: false

jobs:
  include:
    - stage: Documentation
      name: 'Build Documentation'
      script: ./build-documentation.sh
    - stage: Submodule
      name: 'Update Submodule'
      script: ./update-submodule.sh
