export {
  Link,
  NavLink,
  generatePath,
  Prompt,
  MemoryRouter,
  RedirectProps,
  Redirect,
  RouteComponentProps,
  RouteProps,
  Route,
  BrowserRouter as Router,
  HashRouter,
  StaticRouter,
  SwitchProps,
  Switch,
  match,
  matchPath,
  withRouter,
  RouterChildContext,
  useHistory,
  useLocation,
  useParams,
  useRouteMatch,
} from 'react-router-dom';
