export {
  BackButton,
  AndroidBackButton,
  DeepLinking,
  Link,
  match,
  matchPath,
  MemoryRouter,
  Prompt,
  Redirect,
  Route,
  RouteComponentProps,
  RouteProps,
  NativeRouter as Router,
  RouterChildContext,
  StaticRouter,
  Switch,
  withRouter,
  useHistory,
  useLocation,
  useParams,
  useRouteMatch,
} from 'react-router-native';
